env: "mpe"

env_args:
  key: simple_spread_0vis
  map_name: ""
  num_agents: 5
  num_landmarks: 5
  agent_size: 0.15
  time_limit: 60
  
  reward_discrete: False
  reward_rendundant: False # original reward function

standardise_returns: False
standardise_rewards: False

#logs 
use_tensorboard: True
local_results_path: "simple_spread_0vis"
test_greedy: True
test_nepisode: 32
test_interval: 25000
log_interval: 25000
runner_log_interval: 25000
learner_log_interval: 25000

save_model: True # Save the models to disk
save_model_type: "latest"
save_model_interval: 25000 # Save models after this many timesteps

t_max: 10050000