env: "mpe"

env_args:
  key: simple_tag_0vis_colli
  map_name: ""
  num_predators: 9
  num_agents: 9
  predator_size: 0.04
  predator_accel: 5.0
  num_preys: 4
  prey_size: 0.05
  prey_accel: 7.0
  time_limit: 60
  
  reward_discrete: False
  reward_rendundant: False # original reward function

standardise_returns: False
standardise_rewards: False

#logs 
use_tensorboard: True
local_results_path: "simple_tag_0vis_colli"
test_greedy: True
test_nepisode: 32
test_interval: 25000
log_interval: 25000
runner_log_interval: 25000
learner_log_interval: 25000

save_model: True # Save the models to disk
save_model_type: "latest"
save_model_interval: 25000 # Save models after this many timesteps

t_max: 10050000